package com.sorushi.java_dev_hub.utils;

import java.util.LinkedHashMap;
import java.util.Map;
import lombok.Getter;

public class FootballStats {

  @Getter
  protected static final String[] topDivisionClubs = {
    "Real Madrid",
    "FC Barcelona",
    "Manchester United",
    "Liverpool",
    "Chelsea",
    "Arsenal",
    "Manchester City",
    "Bayern Munich",
    "Paris Saint-Germain",
    "Juventus",
    "Inter Milan",
    "AC Milan",
    "Atletico Madrid",
    "Borussia Dortmund",
    "Tottenham Hotspur",
    "Napoli",
    "Benfica",
    "RB Leipzig",
    "Atalanta",
    "AS Roma",
    "Lazio",
    "Ajax",
    "Celtic",
    "Rangers",
    "Club Brugge",
    "Olympiacos",
    "Panathinaikos",
    "Galatasaray",
    "Fenerbahçe",
    "Besiktas",
    "Shakhtar Donetsk",
    "Dynamo Kyiv",
    "Zenit Saint Petersburg",
    "CSKA Moscow",
    "Lokomotiv Moscow",
    "Monaco",
    "Lille",
    "Lyon",
    "Bayer Leverkusen",
    "Eintracht Frankfurt",
    "Werder Bremen",
    "Stuttgart",
    "Freiburg",
    "Mainz 05",
    "Augsburg",
    "Hoffenheim",
    "Leicester City",
    "Newcastle United",
    "Wolverhampton Wanderers",
    "Southampton",
    "Leeds United",
    "Fulham",
    "West Bromwich Albion",
    "FC Copenhagen",
    "FC Midtjylland",
    "Brøndby",
    "Rosenborg",
    "Molde",
    "Vålerenga",
    "AIK",
    "Malmö FF",
    "Djurgårdens IF",
    "Göteborg",
    "Hammarby",
    "HJK Helsinki",
    "RSC Anderlecht",
    "Gent",
    "Genk",
    "KAA Gent",
    "Viktoria Plzeň",
    "Slavia Prague",
    "Sparta Prague",
    "Crvena Zvezda",
    "Partizan Belgrade",
    "Dinamo Zagreb",
    "NK Maribor",
    "Shabab Al Ahli",
    "Al Nassr",
    "Al Hilal",
    "Al Ahly",
    "Zamalek",
    "Esperance de Tunis",
    "Wydad Casablanca",
    "Mamelodi Sundowns",
    "Kaizer Chiefs",
    "Orlando Pirates",
    "Club América",
    "Cruz Azul",
    "Chivas Guadalajara",
    "Monterrey",
    "Tigres UANL",
    "LA Galaxy",
    "Inter Miami CF",
    "Atlanta United",
    "Seattle Sounders FC",
    "New York City FC",
    "D.C. United",
    "Toronto FC",
    "CF Montréal",
    "LAFC",
    "Sporting Kansas City",
    "PSL (Kaizer Chiefs)",
    "Palmeiras",
    "Flamengo",
    "São Paulo FC",
    "Corinthians",
    "Santos",
    "Grêmio",
    "Internacional",
    "Botafogo",
    "Atlético Mineiro",
    "Vasco da Gama",
    "Cruzeiro",
    "River Plate",
    "Boca Juniors",
    "Independiente",
    "Racing Club",
    "San Lorenzo",
    "Vélez Sarsfield",
    "Rosario Central",
    "Estudiantes de La Plata",
    "Colo-Colo",
    "Universidad de Chile",
    "Universidad Católica",
    "Peñarol",
    "Nacional (Uruguay)",
    "LDU Quito",
    "Emelec",
    "Barcelona SC",
    "Independiente del Valle",
    "América de Cali",
    "Atlético Nacional",
    "Millonarios",
    "River Plate (Montevideo)",
    "Danubio",
    "Defensor Sporting",
    "Zamalek SC",
    "Al Masry",
    "Ismaily SC",
    "Pyramids FC",
    "Al Ittihad Alexandria",
    "Esteghlal",
    "Persepolis",
    "Sepahan",
    "Tractor SC",
    "Kashima Antlers",
    "Urawa Red Diamonds",
    "Gamba Osaka",
    "Kawasaki Frontale",
    "FC Tokyo",
    "Yokohama F. Marinos",
    "Al Sadd",
    "Al Duhail",
    "Al Ain FC",
    "Shabab Al Ahli Dubai",
    "Qatar SC",
    "Espérance Tunis",
    "JS Kabylie",
    "TP Mazembe",
    "ZESCO United",
    "Simba SC",
    "Young Africans SC",
    "Auckland City FC",
    "Wellington Phoenix",
    "Sydney FC",
    "Melbourne Victory",
    "Adelaide United",
    "Brisbane Roar",
    "Perth Glory",
    "Victory FC",
    "Blue Bulls FC",
    "Namely",
    "Deportivo Cali",
    "Racing Santander",
    "Real Zaragoza",
    "Valencia CF",
    "Sporting de Gijón",
    "Real Sociedad",
    "Athletic Bilbao",
    "Real Betis",
    "Villarreal CF",
    "Celta Vigo",
    "RCD Espanyol",
    "Mallorca",
    "UD Las Palmas",
    "Elche CF",
    "Granada CF",
    "Deportivo Alavés",
    "Levante UD",
    "Getafe CF",
    "Real Valladolid",
    "Gimnàstic de Tarragona",
    "Portsmouth FC",
    "West Bromwich Albion",
    "Swansea City AFC",
    "Stoke City FC",
    "Norwich City FC",
    "Reading FC",
    "Brighton & Hove Albion",
    "Watford FC",
    "Hull City AFC",
    "Middlesbrough FC",
    "Sunderland AFC",
    "Derby County FC",
    "Ipswich Town FC",
    "Leeds United AFC",
    "Bolton Wanderers FC",
    "Charlton Athletic AFC",
    "Fulham FC",
    "Hibernian FC",
    "Heart of Midlothian FC",
    "Aberdeen FC",
    "Celtic FC",
    "Rangers FC",
    "Motherwell FC",
    "St Johnstone FC",
    "Kilmarnock FC",
    "Dundee United FC",
    "Ross County FC",
    "Livingston FC",
    "Aberdeen FC",
    "Hajduk Split",
    "NK Osijek",
    "NK Rijeka",
    "Slaven Belupo",
    "NK Istra 1961",
    "Rudar Velenje",
    "NK Celje",
    "Maribor",
    "Olimpija Ljubljana",
    "Mura",
    "Nenad Jezic",
    "PAOK FC",
    "Asteras Tripolis FC",
    "Atromitos FC",
    "Panetolikos FC",
    "AEK Athens FC",
    "PAS Giannina FC",
    "Levadiakos FC",
    "Xanthi FC",
    "Rapid Vienna",
    "Austria Vienna",
    "Sturm Graz",
    "LASK Linz",
    "FC Salzburg",
    "Wolfsberger AC",
    "SK Brann",
    "Rosenborg BK",
    "Molde FK",
    "Viking FK",
    "Sandefjord FK",
    "Lillestrøm SK",
    "Odd BK",
    "Vålerenga Fotball",
    "IK Start",
    "Stabæk Fotball",
    "Molde FK",
    "Örebro SK",
    "Djurgårdens IF",
    "AIK Fotboll",
    "IFK Göteborg",
    "IF Elfsborg",
    "Hammarby IF",
    "Kalmar FF",
    "Malmö FF",
    "FC Vaduz",
    "Grasshopper Club Zürich",
    "FC Basel",
    "Young Boys",
    "FC Zürich",
    "FC Sion",
    "St. Gallen",
    "FC Lugano",
    "FC Lausanne-Sport",
    "Neuchâtel Xamax",
    "FC Thun",
    "Vålerenga",
    "Copenhagen",
    "Midtjylland",
    "Brøndby",
    "Odense Boldklub",
    "Aarhus GF",
    "SønderjyskE",
    "Nordsjælland",
    "Brann",
    "Molde",
    "Strømsgodset",
    "Vålerenga",
    "Al Hilal Omdurman",
    "Al Mokawloon",
    "Enyimba FC",
    "TP Mazembe",
    "Zamalek SC",
    "Al Ahly SC",
    "Espérance de Tunis",
    "Wydad AC",
    "Kaizer Chiefs",
    "Mamelodi Sundowns",
    "Orlando Pirates",
    "Bidvest Wits",
    "SuperSport United",
    "Young Africans SC",
    "Simba SC",
    "Stade Malien",
    "ASEC Mimosas",
    "TP Mazembe",
    "AS Vita Club",
    "Enyimba International",
    "Recreativo do Libolo",
    "Raja Casablanca",
    "Club Africain",
    "Guangzhou Evergrande",
    "Beijing Guoan",
    "Shanghai SIPG",
    "Shandong Luneng",
    "Guangzhou R&F",
    "Hebei China Fortune",
    "Shanghai Shenhua",
    "Jiangsu Suning",
    "Kawasaki Frontale",
    "Gamba Osaka",
    "Sanfrecce Hiroshima",
    "Nagoya Grampus",
    "Ulsan Hyundai",
    "Jeonbuk Hyundai Motors",
    "FC Seoul",
    "Suwon Samsung Bluewings",
    "Persepolis",
    "Esteghlal",
    "Sepahan",
    "Tractor SC",
    "Al Sadd SC",
    "Al Duhail SC",
    "Al Rayyan SC",
    "El Jaish SC",
    "Al Gharafa SC",
    "Qatar SC",
    "Al Ain FC",
    "Al Jazira Club",
    "Shabab Al Ahli Dubai",
    "Al Wahda FC",
    "Al Nasr SC (Dubai)",
    "Al Wasl FC",
    "Everton de Viña del Mar",
    "Colo-Colo",
    "Universidad de Chile",
    "Universidad Católica",
    "Club Universidad de Guadalajara",
    "Club León",
    "CF Pachuca",
    "Toluca FC",
    "Club América",
    "Cruz Azul",
    "Chivas Guadalajara",
    "Pumas UNAM",
    "Monterrey",
    "Tigres UANL",
    "Santos Laguna",
    "Necaxa",
    "Atlante",
    "Querétaro FC",
    "Atlas FC",
    "Dorados de Sinaloa",
    "Nacional",
    "Peñarol",
    "Danubio FC",
    "Defensor Sporting",
    "River Plate (Uruguay)",
    "Montevideo Wanderers",
    "Progreso",
    "Villa Española",
    "Liga Deportiva Universitaria Quito",
    "Barcelona SC",
    "Emelec",
    "Aucas",
    "Independiente del Valle",
    "CS Emelec",
    "Deportivo Quito",
    "Universidad Católica de Quito",
    "Atlético Nacional",
    "Millonarios",
    "Independiente Santa Fe",
    "América de Cali",
    "Atlético Deportivo Cali",
    "Danubio",
    "Uruguay Montevideo",
    "River Plate Montevideo",
    "Defensa y Justicia",
    "Unión de Santa Fe",
    "Godoy Cruz",
    "Banfield",
    "Newell’s Old Boys",
    "Rosario Central",
    "Estudiantes de La Plata",
    "Gimnasia y Esgrima La Plata",
    "Huracán",
    "Lanús",
    "Arsenal de Sarandí",
    "San Lorenzo de Almagro",
    "Brighton & Hove Albion",
    "Burnley",
    "Crystal Palace",
    "Fulham",
    "Wolves",
    "Sheffield United",
    "Luton Town",
    "Nottingham Forest",
    "Rangers FC (Scotland)",
    "Celtic FC (Scotland)",
    "Aberdeen FC (Scotland)",
    "Hearts of Midlothian",
    "St Mirren",
    "Ross County",
    "Motherwell FC",
    "Hibernian FC",
    "Western Sydney Wanderers",
    "Melbourne City FC",
    "Wellington Phoenix",
    "Central Coast Mariners",
    "brisbane Roar FC",
    "Adelaide United",
    "Perth Glory",
    "Macarthur FC",
    "Sydney FC (A‑League)",
    "Al Hilal (Sudan)",
    "Al Merrikh",
    "Al Ahly SC (Egypt)",
    "Zamalek SC (Egypt)",
    "Pyramids FC",
    "Ismaily SC",
    "ENPPI Club",
    "Espérance de Tunis",
    "Étoile du Sahel",
    "CS Sfaxien",
    "Raja Casablanca",
    "Wydad Casablanca",
    "TP Mazembe",
    "JS Kabylie",
    "MC Alger",
    "Club Africain",
    "ASEC Mimosas",
    "ASEC Mimosas",
    "ASEC Abidjan",
    "Al Ahly (Cairo)",
    "Ahly Tripoli",
    "Al Ittihad (Libya)",
    "Esperance de Tunis",
    "Kaizer Chiefs",
    "Mamelodi Sundowns",
    "Orlando Pirates",
    "SuperSport United",
    "Young Africans (Tanzania)",
    "Simba SC (Tanzania)",
    "Azam FC",
    "Zanaco FC",
    "Nkana FC",
    "Green Eagles FC",
    "TP Mazembe",
    "AS Vita Club",
    "Enyimba International (Nigeria)",
    "Enugu Rangers",
    "Shooting Stars SC",
    "Heartland FC",
    "Raja Casablanca",
    "Wydad Casablanca",
    "Raja Beni Mellal",
    "Youssoufia Berrechid",
    "Club Africain (Tunisia)",
    "Esperance Tunis",
    "CS Sfaxien",
    "Étoile du Sahel",
    "Gor Mahia FC",
    "AFC Leopards",
    "Tusker FC",
    "Gor Mahia",
    "Elgeco Plus",
    "APR FC (Rwanda)",
    "Rayon Sports (Rwanda)",
    "AS Kigali FC",
    "TP Mazembe",
    "Vita Club (DRCongo)",
    "AS Vita Club",
    "Motema Pembe",
    "ZESCO United FC",
    "Nkana FC",
    "Green Buffaloes FC",
    "Mufulira Wanderers",
    "Power Dynamos FC",
    "Young Africans SC",
    "Simba SC",
    "Yanga SC",
    "Azam FC",
    "Ruvu Shooting",
    "AS Vita Club",
    "TP Mazembe",
    "Al Nassr (Saudi)",
    "Al Hilal (Saudi)",
    "Al Ittihad Jeddah",
    "Al Shabab (Saudi)",
    "Al Ahli (Saudi)",
    "Al Raed FC",
    "Al Faisaly (Saudi)",
    "Al Fateh",
    "Al Taawoun FC",
    "Damac FC",
    "Abha Club",
    "Al Hazm Club",
    "ISL – Mumbai City FC",
    "Mumbai City FC",
    "FC Goa",
    "Kerala Blasters FC",
    "Chennaiyin FC",
    "Hyderabad FC",
    "Bengaluru FC",
    "ATK Mohun Bagan",
    "SC East Bengal",
    "Odisha FC",
    "Jamshedpur FC",
    "NorthEast United FC",
    "Delhi Dynamos",
    "Shillong Lajong FC",
    "NorthEast United",
    "Punjab FC",
    "Churchill Brothers SC",
    "Mohun Bagan SG",
    "Real Kashmir FC",
    "Gokulam Kerala FC",
    "Aizawl FC",
    "Hyderabad FC",
    "Bengaluru FC",
    "Kerala Blasters",
    "Chennaiyin FC",
    "Odisha FC",
    "Delhi FC",
    "Inter Kashi",
    "Al Ain FC (UAE)",
    "Al Wahda FC (UAE)",
    "Al Jazira Club (UAE)",
    "Shabab Al Ahli Dubai (UAE)",
    "Al Nasr (Dubai)",
    "Al Wasl FC (UAE)",
    "Al Ittihad Kalba",
    "Baniyas Club",
    "Kashima Antlers",
    "Urawa Red Diamonds",
    "Consadole Sapporo",
    "Sagan Tosu",
    "Yokohama F. Marinos",
    "FC Tokyo",
    "Kashiwa Reysol",
    "Shimizu S-Pulse",
    "Nagoya Grampus",
    "Vissel Kobe",
    "Kyoto Sanga",
    "Gamba Osaka",
    "Sanfrecce Hiroshima",
    "Vegalta Sendai",
    "Omiya Ardija",
    "Albirex Niigata",
    "Suwon Samsung Bluewings",
    "FC Seoul",
    "Jeonbuk Hyundai Motors",
    "Ulsan Hyundai",
    "Jeju United",
    "Daegu FC",
    "Incheon United",
    "Pohang Steelers",
    "Chonburi FC",
    "Muangthong United",
    "Buriram United",
    "Bangkok United",
    "Port FC",
    "Chennai FC",
    "Lion City Sailors",
    "Home United FC",
    "Tampines Rovers FC",
    "Young Lions FC",
    "Balestier Khalsa FC",
    "Geylang International",
    "Al Sadd SC",
    "Al Duhail SC",
    "Qatar SC",
    "Al Gharafa",
    "Al Rayyan SC",
    "El Jaish SC",
    "Al Wakrah SC",
    "Umm Salal SC",
    "AS Monaco",
    "Nice",
    "Lyon",
    "Marseille",
    "Lens",
    "Metz",
    "Reims",
    "Angers",
    "Montpellier",
    "Bordeaux",
    "Saint-Étienne",
    "Dijon FCO",
    "Lorient",
    "Brest",
    "Nice",
    "FC Zürich",
    "Young Boys",
    "Grasshopper Club Zürich",
    "FC Basel",
    "St. Gallen",
    "Sion",
    "Lugano",
    "Thun",
    "FC Vaduz",
    "Vaduz FC",
    "FC Schaffhausen",
    "FC Lausanne-Sport",
    "Neuchâtel Xamax",
    "Servette FC",
    "FC Winterthur",
    "FC St. Gallen",
    "Grasshopper Zürich",
    "YB Berne",
    "Basel 1893",
    "FC Luzern",
    "Molde FK",
    "Rosenborg BK",
    "Viking FK",
    "Stabæk Fotball",
    "Odd BK",
    "Sandefjord FK",
    "Strømsgodset",
    "Tromsø IL",
    "Athletic Bilbao",
    "Real Sociedad",
    "Espanyol",
    "Celta Vigo",
    "Granada CF",
    "Mallorca",
    "Levante UD",
    "Real Valladolid",
    "Getafe CF",
    "Real Betis",
    "Deportivo La Coruña",
    "Sevilla FC",
    "Real Zaragoza",
    "Sporting Gijón",
    "Elche CF",
    "Almería",
    "RCD Espanyol",
    "Girona FC",
    "Villarreal CF",
    "Cadiz CF",
    "Eibar",
    "Celta Vigo",
    "Osasuna",
    "Real Mallorca",
    "Valencia CF",
    "Rayo Vallecano",
    "Huesca",
    "Cartagena",
    "UD Ibiza",
    "Cádiz CF",
    "Alcoyano",
    "UD Las Palmas",
    "Portsmouth FC",
    "Ipswich Town",
    "Middlesbrough",
    "Sheffield Wednesday",
    "Preston North End",
    "Norwich City",
    "Swansea City",
    "Stoke City",
    "Cardiff City",
    "Hull City",
    "Nottingham Forest",
    "Derby County",
    "Burnley",
    "Brentford",
    "Fulham",
    "West Bromwich Albion",
    "Birmingham City",
    "Aston Villa",
    "Crystal Palace",
    "Everton",
    "Leeds United",
    "West Ham United",
    "Watford",
    "QPR",
    "Reading",
    "Middlesbrough",
    "Ipswich Town",
    "Bolton Wanderers",
    "Charlton Athletic",
    "Wigan Athletic",
    "Blackpool",
    "Bristol City",
    "Derby County",
    "Rotherham United",
    "Sheffield United",
    "Preston North End",
    "Aberdeen FC",
    "Celtic FC",
    "Rangers FC",
    "Hearts of Midlothian",
    "Hibernian FC",
    "Motherwell",
    "Ross County",
    "Dundee United",
    "St Mirren",
    "Kilmarnock",
    "Livingston",
    "Aberdeen",
    "Maribor",
    "Olimpija Ljubljana",
    "NK Domžale",
    "Celje",
    "Viktoria Plzeň",
    "Slavia Prague",
    "Sparta Prague",
    "Sigma Olomouc",
    "Slovan Liberec",
    "Baník Ostrava",
    "Maccabi Tel Aviv",
    "Hapoel Tel Aviv",
    "Beitar Jerusalem",
    "Maccabi Haifa",
    "Bnei Yehuda",
    "Hapoel Be'er Sheva",
    "Lech Poznań",
    "Legia Warsaw",
    "Wisła Kraków",
    "Lechia Gdańsk",
    "Górnik Zabrze",
    "Jagiellonia Białystok",
    "Legia Warsaw",
    "Śląsk Wrocław",
    "Raków Częstochowa",
    "Dinamo Zagreb",
    "Hajduk Split",
    "Rijeka",
    "Osijek",
    "NK Maribor",
    "Zrinjski Mostar",
    "Sarajevo",
    "Velež Mostar",
    "Partizan Belgrade",
    "Red Star Belgrade",
    "Čukarički",
    "Ferencváros",
    "Honvéd",
    "Vasas SC",
    "MTK Budapest",
    "Paks",
    "Ferencváros",
    "Debreceni VSC",
    "Ujpest FC",
    "Shakhtar Donetsk",
    "Dynamo Kyiv",
    "Dnipro",
    "Zorya Luhansk",
    "Karpaty Lviv",
    "Vorskla Poltava",
    "Zenit St. Petersburg",
    "CSKA Moscow",
    "Lokomotiv Moscow",
    "Spartak Moscow",
    "Rubin Kazan",
    "Krasnodar",
    "Legia Warsaw",
    "Red Star Belgrade",
    "Partizan Belgrade",
    "Ferencváros",
    "FC Porto",
    "Benfica",
    "Sporting CP",
    "Braga",
    "Vitória SC",
    "Boavista",
    "Santa Clara",
    "Portimonense",
    "Marítimo",
    "Estoril",
    "Rio Ave",
    "Académica",
    "Paços de Ferreira",
    "Moreirense",
    "Belenenses",
    "Tondela",
    "Ajax",
    "PSV Eindhoven",
    "Feyenoord",
    "AZ Alkmaar",
    "FC Utrecht",
    "FC Groningen",
    "SC Heerenveen",
    "PEC Zwolle",
    "Sparta Rotterdam",
    "Vitesse Arnhem",
    "Willem II",
    "ADO Den Haag",
    "AZ",
    "Twente",
    "NAC Breda",
    "Heracles Almelo",
    "FC Basel",
    "Young Boys",
    "Zurich",
    "St. Gallen",
    "Grasshoppers",
    "Lugano",
    "Servette",
    "Sion",
    "Lausanne",
    "Vaduz",
    "Winterthur",
    "Thun",
    "Rapid Vienna",
    "Austria Vienna",
    "LASK",
    "Sturm Graz",
    "Red Bull Salzburg",
    "WSG Tirol",
    "Wolfsberger AC",
    "Admira Wacker",
    "Levski Sofia",
    "CSKA Sofia",
    "Ludogorets",
    "Botev Plovdiv",
    "Slavia Sofia",
    "Lokomotiv Plovdiv",
    "Arda Kardzhali",
    "Cherno More",
    "Steaua Bucharest",
    "Dinamo Bucharest",
    "CFR Cluj",
    "FCSB",
    "Universitatea Craiova",
    "Rapid Bucharest",
    "Gaz Metan Mediaș",
    "Viitorul Constanța",
    "AEK Athens",
    "Olympiacos",
    "Panathinaikos",
    "PAOK",
    "Aris Thessaloniki",
    "Asteras Tripolis",
    "OFI Crete",
    "Atromitos",
    "Saint-Étienne",
    "Monaco",
    "Marseille",
    "Nice",
    "Lyon",
    "Bordeaux",
    "Toulouse",
    "Lille",
    "Rennes",
    "Nantes",
    "Metz",
    "Montpellier",
    "Reims",
    "Strasbourg",
    "Angers",
    "Cagliari",
    "Hellas Verona",
    "Sassuolo",
    "Udinese",
    "Bologna",
    "Fiorentina",
    "Genoa",
    "Empoli",
    "Salernitana",
    "Venezia",
    "Monza",
    "Torino",
    "Parma",
    "Lecce",
    "SPAL",
    "Cremonese",
    "Catania",
    "Bari",
    "Pisa",
    "Modena",
    "Cosenza",
    "Como",
    "Reggina",
    "Frosinone",
    "Spezia",
    "Perugia",
    "Brescia",
    "Crotone",
    "Livorno",
    "Palermo",
    "Cesena",
    "Salernitana (duplicate possible)",
    "Vicenza",
    "Novara",
    "Triestina",
    "Empoli (duplicate)",
    "Como (duplicate)",
    "Reggiana",
    "Cosenza (duplicate)",
    "Perugia (duplicate)",
    "MFC Lokeren",
    "KV Mechelen",
    "Genk",
    "Standard Liège",
    "Club Brugge",
    "Charleroi",
    "Anderlecht",
    "Gent",
    "Kortrijk",
    "Zulte Waregem",
    "Cercle Brugge",
    "Oostende",
    "KV Oostende",
    "Waasland-Beveren",
    "Sturm Graz",
    "Rapid Vienna",
    "Austria Vienna",
    "Red Bull Salzburg",
    "LASK Linz",
    "Wolfsberger AC",
    "St. Gallen",
    "Grasshopper",
    "Young Boys",
    "Basel",
    "Zürich",
    "Thun",
    "Sion",
    "Lausanne",
    "Servette",
    "Vaduz",
    "Winterthur",
    "Bellinzona",
    "Audax Italiano",
    "Universidad Católica (Chile)",
    "Colo‑Colo",
    "Unión Española",
    "Everton de Viña del Mar",
    "Ñublense",
    "Huachipato",
    "Deportes Iquique",
    "O'Higgins",
    "Santiago Wanderers",
    "Palestino",
    "Universidad de Chile",
    "Cobreloa",
    "Universidad de Concepción",
    "Antofagasta",
    "Bolívar",
    "The Strongest",
    "Oriente Petrolero",
    "Independiente Petrolero",
    "San José",
    "Wilstermann",
    "Blooming",
    "Nacional Potosí",
    "Real Potosí",
    "Aurora",
    "Guabirá",
    "Wilstermann (duplicate)",
    "Defensor Sporting",
    "Danubio",
    "Peñarol",
    "Nacional (Uruguay)",
    "Club Atlético River Plate",
    "Peñarol (duplicate)",
    "Club Deportivo Maldonado",
    "Montevideo Wanderers",
    "Progreso",
    "Plaza Colonia",
    "Sud América",
    "Unión de Santa Fe",
    "Racing Club",
    "Independiente",
    "Boca Juniors",
    "River Plate (Argentina)",
    "Gimnasia y Esgrima La Plata",
    "Estudiantes",
    "Rosario Central",
    "Newell's Old Boys",
    "Arsenal de Sarandí",
    "Lanús",
    "Huracán",
    "Banfield",
    "Argentinos Juniors",
    "Talleres",
    "Belgrano",
    "Godoy Cruz",
    "Vélez Sarsfield",
    "San Lorenzo",
    "Atlas",
    "Tigres UANL",
    "Monterrey",
    "Club América",
    "Cruz Azul",
    "Pachuca",
    "Toluca",
    "León",
    "Pumas UNAM",
    "Querétaro",
    "Club Tijuana",
    "Atlético San Luis",
    "Mazatlán FC",
    "Santos Laguna",
    "Necaxa",
    "Chivas Guadalajara",
    "Mazatlán (duplicate)",
    "FC Dallas",
    "LAFC",
    "Houston Dynamo",
    "Philadelphia Union",
    "New York Red Bulls",
    "Chicago Fire",
    "DC United",
    "Colorado Rapids",
    "Minnesota United",
    "Vancouver Whitecaps",
    "Toronto FC",
    "CF Montréal",
    "Seattle Sounders",
    "Portland Timbers",
    "Orlando City SC",
    "Inter Miami CF",
    "Nashville SC",
    "Charlotte FC",
    "St. Louis CITY SC",
    "FC Cincinnati",
    "San Jose Earthquakes",
    "Real Salt Lake",
    "Sporting Kansas City",
    "New England Revolution",
    "Atlanta United",
    "Toronto FC (duplicate)",
    "CF Montréal (duplicate)",
    "LA Galaxy",
    "New York City FC",
    "FC Seoul",
    "Jeonbuk Hyundai Motors",
    "Ulsan Hyundai",
    "Suwon Samsung Bluewings",
    "Incheon United",
    "Daegu FC",
    "Jeju United",
    "Pohang Steelers",
    "Seongnam FC",
    "Gwangju FC",
    "Gangwon FC",
    "Daejeon Hana Citizen",
    "KITCHEEN FC",
    "Kitchee",
    "Eastern SC",
    "South China AA",
    "Lee Man",
    "R&F (Hong Kong)",
    "Hong Kong Pegasus",
    "Bengaluru FC",
    "Mumbai City FC",
    "Kerala Blasters FC",
    "ATK Mohun Bagan",
    "Chennaiyin FC",
    "FC Goa",
    "Hyderabad FC",
    "Jamshedpur FC",
    "NorthEast United FC",
    "Odisha FC",
    "SC East Bengal",
    "Churchill Brothers",
    "Gokulam Kerala",
    "Real Madrid Castilla",
    "Barcelona B",
    "Atletico Madrid B",
    "Valencia Mestalla",
    "Real Betis B",
    "Sevilla Atlético",
    "Deportivo Fabril",
    "Sporting B",
    "FC Barcelona B",
    "Juventus U23",
    "Inter Milan Primavera",
    "Milan Primavera",
    "RB Leipzig II",
    "Bayern Munich II",
    "Borussia Dortmund II",
    "Hertha BSC II",
    "Schalke 04 II",
    "St. Pauli II",
    "Ajax II",
    "PSV Eindhoven II",
    "Feyenoord U21",
    "Red Bull Salzburg II",
    "Rapid Vienna II",
    "GAK 1902",
    "Atlético Mineiro list duplicates",
    "Vasco da Gama duplicates",
    "Cruzeiro duplicates",
    "Flamengo duplicates"
  };

  private FootballStats() {}

  public static Map<String, String> getClubCountryMap() {
    Map<String, String> map = new LinkedHashMap<>();

    // England
    String[] england = {
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton & Hove Albion",
      "Burnley",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Sunderland",
      "Tottenham Hotspur",
      "West Ham United",
      "Wolverhampton Wanderers"
    };
    for (String club : england) map.put(club, "England");

    // Italy
    String[] italy = {
      "AC Milan",
      "Inter Milan",
      "Juventus",
      "Napoli",
      "AS Roma",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "Bologna",
      "Cagliari",
      "Como 1907",
      "Cremonese",
      "Genoa",
      "Hellas Verona",
      "Parma Calcio 1913",
      "US Lecce",
      "Sassuolo",
      "Pisa Sporting Club",
      "Torino",
      "Udinese"
    };
    for (String club : italy) map.put(club, "Italy");

    // Spain
    String[] spain = {
      "Real Madrid",
      "FC Barcelona",
      "Atlético Madrid",
      "Real Sociedad",
      "Athletic Bilbao",
      "Valencia CF",
      "Villarreal CF",
      "Real Betis",
      "Sevilla FC",
      "Girona FC",
      "Celta de Vigo",
      "Getafe CF",
      "CA Osasuna",
      "RCD Mallorca",
      "RCD Espanyol",
      "Rayo Vallecano",
      "Deportivo Alavés",
      "Levante UD",
      "Real Oviedo",
      "Elche CF"
    };
    for (String club : spain) map.put(club, "Spain");

    // Germany
    String[] germany = {
      "Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "Eintracht Frankfurt",
          "SC Freiburg",
      "VfB Stuttgart", "VfL Wolfsburg", "Borussia Mönchengladbach", "Union Berlin", "RB Leipzig"
    };
    for (String club : germany) map.put(club, "Germany");

    // France
    String[] france = {
      "Paris Saint‑Germain",
      "Olympique Marseille",
      "AS Monaco",
      "Lille OSC",
      "OGC Nice",
      "Lens",
      "Rennes",
      "Lyon",
      "Auxerre",
      "Angers SCO",
      "Le Havre AC",
      "Lorient",
      "Paris FC",
      "Metz",
      "Brest",
      "Strasbourg",
      "Toulouse",
      "Nantes"
    };
    for (String club : france) map.put(club, "France");

    // Portugal
    String[] portugal = {
      "SL Benfica", "FC Porto", "Sporting CP", "SC Braga", "Vitória Guimarães", "Estoril Praia",
      "Gil Vicente", "Casa Pia AC", "Moreirense FC", "CD Nacional", "Rio Ave FC", "FC Arouca",
      "CD Alverca", "AVS Futebol", "CF Estrela Amadora", "FC Famalicão", "Santa Clara", "CD Tondela"
    };
    for (String club : portugal) map.put(club, "Portugal");

    // Netherlands
    String[] netherlands = {
      "Ajax",
      "PSV Eindhoven",
      "Feyenoord",
      "AZ Alkmaar",
      "FC Utrecht",
      "FC Twente",
      "Go Ahead Eagles",
      "NEC Nijmegen",
      "SC Heerenveen",
      "Sparta Rotterdam",
      "FC Groningen",
      "Fortuna Sittard",
      "NAC Breda",
      "Heracles Almelo",
      "Excelsior",
      "SC Telstar",
      "FC Volendam"
    };
    for (String club : netherlands) map.put(club, "Netherlands");

    // Belgium
    String[] belgium = {
      "RSC Anderlecht",
      "Club Brugge KV",
      "Standard Liège",
      "KAA Gent",
      "Royal Antwerp",
      "Sint‑Truidense VV",
      "Royal Charleroi SC",
      "OH Leuven",
      "KVC Westerlo",
      "Zulte Waregem",
      "Dender EH",
      "La Louvière",
      "Union Saint‑Gilloise",
      "KV Mechelen",
      "Cercle Brugge KSV",
      "Oud‑Heverlee Leuven",
      "FCV Dender EH",
      "RAAL La Louvière",
      "KRC Genk"
    };
    for (String club : belgium) map.put(club, "Belgium");

    // Austria
    String[] austria = {
      "Red Bull Salzburg",
      "SK Sturm Graz",
      "SK Rapid Wien",
      "Austria Wien",
      "LASK",
      "SV Ried",
      "Grazer AK",
      "Wolfsberger AC",
      "TSV Hartberg",
      "WSG Tirol"
    };
    for (String club : austria) map.put(club, "Austria");

    return map;
  }
}
